//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumImage
    {
        public long Id { get; set; }
        public long AlbumId { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
        public string ImageSource { get; set; }
        public string Desctiption { get; set; }
        public int Order { get; set; }
        public string ShareTitle { get; set; }
        public string ShareKeyword { get; set; }
        public string ShareDescription { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
