//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public Albums()
        {
            this.AlbumImages = new HashSet<AlbumImages>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Attribute { get; set; }
        public int Order { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ShareTitle { get; set; }
        public string ShareKeyword { get; set; }
        public string ShareDescription { get; set; }
    
        public virtual ICollection<AlbumImages> AlbumImages { get; set; }
    }
}
