//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsNew
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> NewId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public int Rate { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> MofifyDate { get; set; }
    }
}
