//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendlyUrl
    {
        public int Id { get; set; }
        public string NameLink { get; set; }
        public string Link { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string NameSpaces { get; set; }
        public int Order { get; set; }
        public Nullable<long> ItemId { get; set; }
    }
}
