//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.Catalogs_Manufacturers = new HashSet<Catalogs_Manufacturers>();
            this.Products = new HashSet<Products>();
        }
    
        public long Id { get; set; }
        public string ManufacturerName { get; set; }
        public string Code { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ShareTitle { get; set; }
        public string ShareKeyword { get; set; }
        public string ShareDescription { get; set; }
    
        public virtual ICollection<Catalogs_Manufacturers> Catalogs_Manufacturers { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
