//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberProfile
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long LocationId { get; set; }
        public string Address { get; set; }
        public string Emaill { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public int Sex { get; set; }
        public string Pid { get; set; }
        public string ZipCode { get; set; }
        public string Photo { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
