//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSitting
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string SDT { get; set; }
        public string TimeNote { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> Ishow { get; set; }
        public Nullable<int> Order { get; set; }
        public string City { get; set; }
    }
}
