//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public string ImgSource { get; set; }
        public long IsAvatar { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
