//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopSupport
    {
        public long Id { get; set; }
        public string SupportName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }
        public string Yahoo { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
