//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public long Id { get; set; }
        public string TagName { get; set; }
        public string TagUrl { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string SeoTitle { get; set; }
        public string SeoKeyword { get; set; }
        public string SeoDescription { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ShareTitle { get; set; }
        public string ShareKeyword { get; set; }
        public string ShareDescription { get; set; }
        public string ImageSource { get; set; }
    }
}
