//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public long Id { get; set; }
        public string VideoName { get; set; }
        public string VideoUrl { get; set; }
        public string VideoDecription { get; set; }
        public string VideoLink { get; set; }
        public string VideoImage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string SeoTitle { get; set; }
        public string SeoKeyword { get; set; }
        public string SeoDescription { get; set; }
        public string VideoName_EN { get; set; }
    }
}
